[NGPDCP-2823] Add new variant for badge component
comfortdelgro/compass-design pull request #1034
Opened 2023-08-18 04:34 UTC by hoapn-fsoft

# Add new variant for badge component

## Description

**1) Screenshot

<img width="1691" alt="image" src="https://github.com/comfortdelgro/compass-design/assets/128688086/7a501e4c-f478-421a-8338-04badbcc72da">

**2) Changes**

**3) Impact**

## Reference (optional)

## Check list

- [x] 1. Did you start and verify your changes?
- [x] 2. Did you run build to make sure that your changes can be built successfully?
- [x] 3. No !important flag, inline style in css
- [x] 4. No boilerplate codes (1)
- [x] 5. No duplicate code that exist in common functions?
- [x] 6. All of defined variables should have default value, check null and undefined?
- [x] 7. Use meaningful name for variables, no suffix 1,2,... Describes reference information for easier to understand what's inside. (2)
- [x] 9. Unsubscribed all of subscribers and even listeners when you don't need them.

```
(1)
Boilerplate codes is duplicated multiple times a bunch of the same code. This should be a common function to reuse through your code or you can use generic class / methods or design pattern to avoid the Boilerplate codes.
```

```
(2)
Follow theo coding convention
NO acronym variable name:
WRONG: el, elm
RIGHT: element
Your code can be read as a sentence
```

2023-08-18 07:23 UTC, pieliedie requested changes

2023-08-18 07:23 UTC, pieliedie commented on packages/react-compass/src/badge/badge.styles.ts
> +        background: '$white',
![image](https://github.com/comfortdelgro/compass-design/assets/7071853/52e4c214-7d0e-4bcf-b3b8-e4dcd14fe419)
dark mode

2023-08-18 07:23 UTC, pieliedie commented on packages/react-compass/src/badge/badge.tsx
> +  revert?: boolean
`isReverted`

2023-08-18 10:39 UTC, hoapn-fsoft commented on packages/react-compass/src/badge/badge.tsx
> +  revert?: boolean
Updated, thank @pieliedie

2023-08-18 10:39 UTC, hoapn-fsoft commented on packages/react-compass/src/badge/badge.styles.ts
> +        background: '$white',
updated

2023-08-21 01:12 UTC, pieliedie approved these changes

2023-08-21 02:54 UTC, Tai-Chi-Bui approved these changes

2023-08-21 02:54 UTC, merged