[NGPDCP-2595] PUDO component
comfortdelgro/compass-design pull request #1036
Opened 2023-08-18 08:49 UTC by kaiceresy

## Description

**1) Changes**

Add PUDO component for the H5 project.

https://comfortdelgrotaxi.atlassian.net/browse/NGPDCP-2595

![image](https://github.com/comfortdelgro/compass-design/assets/142210010/b31134c2-f21a-42c4-84c7-880f5db16c31)
![image](https://github.com/comfortdelgro/compass-design/assets/142210010/caa0904c-f28a-4827-b303-ea1dde1328c1)
![image](https://github.com/comfortdelgro/compass-design/assets/142210010/bb30e4b4-f87e-4dfd-be28-4d47b6896697)

**2) Impact**

No

## Check list

- [x] 1. Did you start and verify your changes?
- [x] 2. Did you run build to make sure that your changes can be built successfully?
- [x] 3. No !important flag, inline style in css
- [x] 4. No boilerplate codes (1)
- [x] 5. No duplicate code that exist in common functions?
- [x] 6. All of defined variables should have default value, check null and undefined?
- [x] 7. Use meaningful name for variables, no suffix 1,2,... Describes reference information for easier to understand what's inside. (2)
- [x] 9. Unsubscribed all of subscribers and even listeners when you don't need them.

```
(1)
Boilerplate codes is duplicated multiple times a bunch of the same code. This should be a common function to reuse through your code or you can use generic class / methods or design pattern to avoid the Boilerplate codes.
```

```
(2)
Follow theo coding convention
NO acronym variable name:
WRONG: el, elm
RIGHT: element
Your code can be read as a sentence
```

2023-08-21 15:36 UTC, hoapn-fsoft commented
![image](https://github.com/comfortdelgro/compass-design/assets/128688086/48cbb607-3c25-4e58-9d38-64fe15ff34be)
![image](https://github.com/comfortdelgro/compass-design/assets/128688086/dd39b973-7963-4b72-8cdd-f7823b1b39a8)

some errors related to type

2023-08-21 15:37 UTC, hoapn-fsoft commented
![image](https://github.com/comfortdelgro/compass-design/assets/128688086/71dadd70-1f38-44ee-b347-3196346d59e7)
When I swap 2 destination, always focus on the 2nd item

2023-08-21 15:41 UTC, hoapn-fsoft requested changes

2023-08-21 15:41 UTC, hoapn-fsoft commented on packages/react-compass/src/pudo/pudo-item.tsx
> +      css={{...css, zIndex: itemsLength - 1 - index ?? undefined}}
using useMemo

2023-08-21 15:41 UTC, hoapn-fsoft commented on packages/react-compass/src/pudo/pudo.tsx
> +    onValuesChange?.(newPudoObjValues, newPudoArrValues)
using debounce

2023-08-22 02:00 UTC, hoapn-fsoft commented
> > ![image](https://user-images.githubusercontent.com/128688086/262073287-71dadd70-1f38-44ee-b347-3196346d59e7.png) When I swap 2 destination, always focus on the 2nd item
> 
> So what are your expectations? Always focus on the last item or sth more dynamic?
> 
> According to the input UI/order, users tend to write/input from top to bottom items. If they do swap the 2nd with the 3rd item, there are higher chances that the 2nd input is empty, and if users need to update the value of the swap pair, again top to bottom. So keep focusing on the new 2nd item that makes sense and less code tho.

Don't focus on any item when the user swaps. Focus is only shown when the user is entering that item

2023-08-22 06:15 UTC, pieliedie approved these changes

2023-08-22 14:47 UTC, hoapn-fsoft approved these changes

2023-08-22 14:47 UTC, merged