[NGPDC-2597] confirm PU point component
comfortdelgro/compass-design pull request #1041
Opened 2023-08-21 16:45 UTC by pieliedie

# Merge request description template

## Description

**1) Root cause**

**2) Changes**

Add new Confirm PU Point component.

![image](https://github.com/comfortdelgro/compass-design/assets/7071853/e9d2b79d-53cc-4f03-80d3-53c7a2aac3c9)
![image](https://github.com/comfortdelgro/compass-design/assets/7071853/6c5cf900-07b1-4009-8d16-ec01b1aabfc6)

**3) Impact**

## Reference (optional)

## Check list

- [x] 1. Did you start and verify your changes?
- [x] 2. Did you run build to make sure that your changes can be built successfully?
- [x] 3. No !important flag, inline style in css
- [x] 4. No boilerplate codes (1)
- [x] 5. No duplicate code that exist in common functions?
- [x] 6. All of defined variables should have default value, check null and undefined?
- [x] 7. Use meaningful name for variables, no suffix 1,2,... Describes reference information for easier to understand what's inside. (2)
- [x] 9. Unsubscribed all of subscribers and even listeners when you don't need them.

```
(1)
Boilerplate codes is duplicated multiple times a bunch of the same code. This should be a common function to reuse through your code or you can use generic class / methods or design pattern to avoid the Boilerplate codes.
```

```
(2)
Follow theo coding convention
NO acronym variable name:
WRONG: el, elm
RIGHT: element
Your code can be read as a sentence
```

2023-08-21 17:11 UTC, hoapn-fsoft requested changes

2023-08-21 17:11 UTC, hoapn-fsoft commented on packages/react-compass/src/confirm-pickup/confirm-pickup.tsx
> +            placeholder='E.g. Lobby, side entrance, etc'
placeholder should be taken from prop

2023-08-21 17:11 UTC, hoapn-fsoft commented on packages/react-compass/src/confirm-pickup/confirm-pickup.tsx
> +            onChange={handleEditPUPoint}
```suggestion
            onChange={handleChangeInput}

```

2023-08-22 03:04 UTC, pieliedie commented on packages/react-compass/src/confirm-pickup/confirm-pickup.tsx
> +            placeholder='E.g. Lobby, side entrance, etc'
fixed. Thanks @hoapn-fsoft

2023-08-22 03:38 UTC, hoapn-fsoft approved these changes
LGTM

2023-08-22 06:16 UTC, merged