[NGPDCP-2927] Slide action/Swiper component
comfortdelgro/compass-design pull request #1070
Opened 2023-08-30 10:16 UTC by kaiceresy

## Description

**1) Changes**

Add Slide action/Swiper component for H5 project.

**2) Impact**

the `useDrag` hooks

**3) UI Preview**

![image](https://github.com/comfortdelgro/compass-design/assets/142210010/a100fb28-0552-4840-85a2-bf11053775a7)
![image](https://github.com/comfortdelgro/compass-design/assets/142210010/20fa5266-b81a-4e0e-bddd-16303f8c47ab)
![image](https://github.com/comfortdelgro/compass-design/assets/142210010/d6c16ace-93b2-49a9-b1c5-5e44152426c3)

## Reference (optional)

[NGPDCP-2927](https://comfortdelgrotaxi.atlassian.net/browse/NGPDCP-2927)

## Check list

- [x] 1. Did you start and verify your changes?
- [x] 2. Did you run build to make sure that your changes can be built successfully?
- [x] 3. No !important flag, inline style in css
- [x] 4. No boilerplate codes (1)
- [x] 5. No duplicate code that exist in common functions?
- [x] 6. All of defined variables should have default value, check null and undefined?
- [x] 7. Use meaningful name for variables, no suffix 1,2,... Describes reference information for easier to understand what's inside. (2)
- [x] 9. Unsubscribed all of subscribers and even listeners when you don't need them.

```
(1)
Boilerplate codes is duplicated multiple times a bunch of the same code. This should be a common function to reuse through your code or you can use generic class / methods or design pattern to avoid the Boilerplate codes.
```

```
(2)
Follow theo coding convention
NO acronym variable name:
WRONG: el, elm
RIGHT: element
Your code can be read as a sentence
```

[NGPDCP-2927]: https://comfortdelgrotaxi.atlassian.net/browse/NGPDCP-2927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-08-31 07:06 UTC, hoapn-fsoft requested changes

2023-08-31 07:06 UTC, hoapn-fsoft commented on packages/react-compass/src/slide-action/slide-action.styles.ts
> +    bgType: {
```suggestion
    backgroundType: {
```

avoid abbreviations

2023-08-31 07:06 UTC, hoapn-fsoft commented on packages/react-compass/src/slide-action/slide-action.styles.ts
> +    slideBg: {
```suggestion
    slideBackground: {
```

avoid abbreviations

2023-08-31 07:06 UTC, hoapn-fsoft commented on packages/react-compass/src/slide-action/slide-action.tsx
> +    const SlideRef = useDOMRef<HTMLDivElement>(ref)
```suggestion
    const slideRef = useDOMRef<HTMLDivElement>(ref)
```

2023-08-31 07:06 UTC, hoapn-fsoft commented on packages/react-compass/src/slide-action/slide-action.tsx
> +    const SlideBgRef = useRef<HTMLDivElement>(null)
```suggestion
    const slideBgRef = useRef<HTMLDivElement>(null)
```

2023-08-31 07:06 UTC, hoapn-fsoft commented on packages/react-compass/src/slide-action/slide-action.tsx
> +    const SlideLabelRef = useRef<HTMLDivElement>(null)
```suggestion
    const slideLabelRef = useRef<HTMLDivElement>(null)
```

2023-08-31 07:06 UTC, hoapn-fsoft commented on packages/react-compass/src/slide-action/slide-action.tsx
> +        // SlideBgRef.current.style.setProperty('transform', transform)
remove comment

2023-08-31 07:06 UTC, hoapn-fsoft commented on packages/react-compass/src/slide-action/slide-action.tsx
> +        const bgOpacity = x / maxSlideDistance - 0.4
create constant for 0.4 value

2023-08-31 07:06 UTC, hoapn-fsoft commented on packages/react-compass/src/slide-action/slide-dragger.tsx
> +  const SlideDragElement = slideDragRef.current
```suggestion
  const slideDragElement = slideDragRef.current
```

2023-08-31 07:06 UTC, hoapn-fsoft commented
Error type
<img width="966" alt="image" src="https://github.com/comfortdelgro/compass-design/assets/128688086/84f628d5-3a6d-4816-b843-5d87f07f8934">

2023-08-31 09:52 UTC, hoapn-fsoft approved these changes
LGTM

2023-08-31 11:28 UTC, pieliedie approved these changes

2023-09-02 08:02 UTC, hoapn-fsoft approved these changes

2023-09-02 08:02 UTC, merged