Bug/fix speed dial
comfortdelgro/compass-design pull request #793
Opened 2023-06-14 08:02 UTC by yagin94

## I'm raising pull request for:

- [Feature](?template=feature_template.md)
- [Bugfix](?template=bugfix_template.md)

2023-06-15 10:04 UTC, fpt-duongtx requested changes

2023-06-15 10:04 UTC, fpt-duongtx commented on packages/react-compass/src/speed-dial/speed-dial.tsx
> +              height: '27.43px',
Need to check with odd number like this

2023-06-15 10:04 UTC, fpt-duongtx commented on packages/react-compass/src/speed-dial/speed-dial.tsx
> +          <span
Inline style might block the other to override the style, it should be class name or options

2023-06-16 08:47 UTC, fpt-duongtx approved these changes

2023-06-16 09:03 UTC, Tai-Chi-Bui approved these changes

2023-06-16 09:03 UTC, merged